### ISSUE TITLE
Destination cannot be modified

### ISSUE THREAD

**Issue by marsh-harv** [garden-of-delete/airbyte-tentacle#33]
I have tried various different destinations to configure and every time I get the same error. 

I want to set up a LocalJSON destination.  My config is as below:

```
destinations:
  - name: demo-dest 
    destinationName: LocalJSON
    connectionConfiguration:
      destination_path: '/json_output'
```

error recieved: 

```
API connection is healthy: True
Retrieving source and destination definitions from: http://localhost:8000/
Retrieving Airbyte configuration from: http://localhost:8000/
Applying changes to deployment: http://localhost:8000/
Error: unable to modify destination: LocalJSON
Response code: 400 Error: Unrecognized response code
```

Is there a catalog of config setups being worked on to help users or can you spot something I have missed?
